### ISSUE TITLE
Newer Version of Robin Hood Hashing

### ISSUE THREAD

**Issue by jwillikers** [p-ranav/csv#19]
Newer versions of [Robin Hood](https://github.com/martinus/robin-hood-hashing) seem to address several compiler warnings and errors. I can't currently compile my project with GCC 9.1.1 on RHEL 7.7 because of this.

**Comment by p-ranav** [comment]
Have you already bumped it on your fork? If so, do you want to create a pull request?

**Comment by jwillikers** [comment]
Yep, I'm working on a PR for you right now.
